title: [Castelo Lopes vis천es e opini천es pessoai]
description: [CasteLopes - Partilha das minhas vis천es e opini천es pessoais]




theme: jekyll-theme-minimal


logo: [/assets/images/Castelo-Lopes-logo.jpeg]
show_downloads: [false]  # "true" or "false" to indicate whether to provide a download URL]
google_analytics: []  # [Your Google Analytics tracking ID]



plugins:
  - jekyll-redirect-from


